export const moviesList = [
  {
    name: "Due Date",
    year: 2010,
    runtime: 95,
    categories: ["comedy", "adventure"],
    "release-date": "2010-11-05",
    director: "Todd Phillips",
    writer: [
      "Alan R. Cohen",
      "Alan Freedland",
      "Adam Sztykiel",
      "Todd Phillips",
    ],
    actors: [
      "Robert Downey Jr.",
      "Zach Galifianakis",
      "Michelle Monaghan",
      "Jamie Foxx",
    ],
    storyline:
      "Businessman and first time father (to-be), Peter Highman's in Atalanta trying to get home to LA, where how wife's about to give birth, but after getting kicked off a plane, due to his seat mate, the pair end up trying to hitch a rideto the west coast.",
  },
  {
    name: "Harry Potter and the Deathly Hallows: Part 1",
    year: 2010,
    runtime: 146,
    categories: ["adventure", "family", "fantasy"],
    "release-date": "2010-11-19",
    director: "David Yates",
    writer: ["Steve Kloves", "J.K. Rowling"],
    actors: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
    description:
      "Nominated for two Oscars, Harry Potter and the Deathly Hallows - Part 1 begins as Harry, Ron and Hermione set out on their perilous mission to track down and destroy the secret to Voldemort’s immortality and destruction—the Horcruxes. \n On their own, without the guidance of their professors or the protection of Professor Dumbledore, the three friends must now rely on one another more than ever. But there are Dark Forces in their midst that threaten to tear them apart. \n Meanwhile, the wizarding world has become a dangerous place for all enemies of the Dark Lord. The long-feared war has begun and Voldemort’s Death Eaters seize control of the Ministry of Magic and even Hogwarts, terrorizing and arresting anyone who might oppose them. But the one prize they still seek is the one most valuable to Voldemort: Harry Potter. \n The Chosen One has become the hunted one as the Death Eaters search for Harry with orders to bring him to Voldemort… alive. Harry’s only hope is to find the Horcruxes before Voldemort finds him, but as he searches for clues, he uncovers an old and almost forgotten tale—the legend of the Deathly Hallows.",
  },
  {
    name: "How To Train Your Dragon",
    year: 2010,
    runtime: 98,
    categories: [
      "animation",
      "action",
      "adventure",
      "comedy",
      "fantasy",
      "family",
    ],
    "release-date": "2010-03-26",
    director: ["Dean DeBlois", "Chris Sanders"],
    writer: [
      "William Davies",
      "Dean DeBlois",
      "Chris Sanders",
      "Cressida Cowell",
      "Adam F. Goldberg",
    ],
    actors: ["Jay Baruchel", "Gerard Butler", "Christopher Mintz-Plasse"],
    storyline:
      "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.",
  },
  {
    name: "Inception",
    year: 2010,
    runtime: 148,
    categories: ["adventure", "action", "sci-fi", "thriller"],
    "release-date": "2010-07-16",
    director: "Christopher Nolan",
    writer: ["Christopher Nolan"],
    actors: [
      "Leonardo DiCaprio",
      "Joseph Gordon-Levitt",
      "Ellen Page",
      "Tom Hardy",
      "Ken Watanabe",
      "Dileep Rao",
      "Cillian Murphy",
      "Marion Cotillard",
      "Tom Berenger",
    ],
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
  },
  {
    name: "Iron Man 2",
    year: 2010,
    runtime: 124,
    categories: ["adventure", "action", "sci-fi"],
    "release-date": "2010-05-07",
    director: "Jon Favreau",
    writer: [
      "Justin Theroux",
      "Stan Lee",
      "Don Heck",
      "Larry Lieber",
      "Jack Kirby",
    ],
    actors: ["Robert Downey Jr", "Gwyneth Paltrow", "Mickey Rourke"],
    storyline:
      'With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press, and the public to share his technology with the military. Unwilling to let go of his invention, Stark, along with Pepper Potts, and James "Rhodey" Rhodes at his side, must forge new alliances - and confront powerful enemies',
  },
  {
    name: "Percy Jackson and the Olympians: The Lightning Thief",
    year: 2010,
    runtime: 119,
    categories: ["adventure", "family", "fantasy"],
    "release-date": "2010-02-02",
    director: "Chris Columbus",
    writer: ["Craig Titley", "Rick Riordan"],
    actors: [
      "Logan Lerman",
      "Brandon T. Jackson",
      "Alexandra Daddario",
      "Jake Abel",
      "Sean Bean",
      "Kevin McKidd",
      "Steve Coogan",
      "Melina Kanakaredes",
      "Rosario Dawson",
      "Dylan Neal",
      "Erica Cerra",
      "Stefanie von Pfetten",
      "Dimitri Lekkos",
      "Ona Grauer",
      "Serinda Swan",
      "Conrad Coates",
      "Ray Winstone",
      "Luke Camilleri",
      "Uma Thurman",
      "Pierce Brosnan",
      "Maria Olsen",
      "Julian Richings",
      "Catherine Keener",
      "Joe Pantoliano",
    ],
    description:
      "Always trouble-prone, the life of teenager Percy Jackson (Logan Lerman) gets a lot more complicated when he learns he's the son of the Greek god Poseidon. At a training ground for the children of deities, Percy learns to harness his divine powers and prepare for the adventure of a lifetime: he must prevent a feud among the Olympians from erupting into a devastating war on Earth, and rescue his mother from the clutches of Hades, god of the underworld.",
  },
  {
    name: "Red",
    year: 2010,
    runtime: 111,
    categories: ["comedy", "action", "crime"],
    "release-date": "2010-10-15",
    director: "Robert Schwentke",
    writer: ["Jon Hoeber", "Erich Hoeber"],
    actors: [
      "Bruce Willis",
      "Mary-Louise Parker",
      "Morgan Freeman",
      "John Malkovich",
      "Helen Mirren",
      "Karl Urban",
    ],
    description:
      "Retired government agents uncover a plot against their lives, and hilarity ensues as they look for the truth.",
  },
  {
    name: "Resident Evil 4: Afterlife",
    year: 2010,
    runtime: 96,
    categories: ["horror", "action", "adventure"],
    "release-date": "2010-09-17",
    director: "Paul W. S. Anderson",
    writer: "Paul W. S. Anderson",
    actors: [
      "Milla Jovovich",
      "Ali Larter",
      "Shawn Roberts",
      "Wentworth Miller",
      "Sienna Guillory",
    ],
    storyline:
      "In a world ravaged by a virus infection, turning its victims into the Undead, Alice (Jovovich), continues on her journey to find survivors and lead them to safety. Her deadly battle with the Umbrella Corporation reaches new heights, but Alice gets some unexpected help from an old friend. A new lead that promises a safe haven from the Undead takes them to Los Angeles, but when they arrive the city is overrun by thousands of Undead - and Alice and her comrades are about to step into a deadly trap.",
  },
  {
    name: "The Book of Eli",
    year: 2010,
    runtime: 118,
    categories: ["adventure", "action", "drama", "thriller"],
    "release-date": "2010-03-18",
    director: "The Hughes Brothers",
    writer: ["Gary Whitta"],
    actors: ["Denzel Washington", "Mila Kunis", "Ray Stevenson"],
    description:
      "In a violent post-apocalyptic society, a drifter, Eli, has been wandering westward across North America for the last thirty years. He finds solace in a unique book which he carries on his person and guards closely, whilst surviving by hunting small animals and seeking goods in destroyed houses and vehicles to trade in villages for water and supplies. When he reaches a village ruled by the powerful mobster, Carnegie, the man views Eli's impressive fighting skills and offers Eli a place within his gang. Carnegie presses his blind lover Claudia to send her daughter, Solara, to at least convince Eli to spend the night by sleeping with him. However, Eli proves to be the better man when he gently declines her advances. The girl sees Eli's book, and when Carnegie finds out he beats her mother until she reveals what she saw. Carnegie sends his gang into the wasteland to take the book from Eli, but the man proves to be a formidable foe as he makes it more than clear that if they want the book,...",
  },
  {
    name: "The Social Network",
    year: 2010,
    runtime: 120,
    categories: ["biography", "drama"],
    "release-date": "2010-10-01",
    director: "David Fincher",
    writer: ["Aaron Sorkin", "Ben Mezrich"],
    actors: [
      "Jesse Eisenberg",
      "Justin Timberlake",
      "Rooney Mara",
      "Joseph Mazzello",
      "Andrew Garfield",
    ],
    storyline:
      "Harvard student Mark Zuckerberg creates a social networking site that would become Facebook and is later sued by two brothers who claimed that Zuckerberg stole their idea and the co-founder who was pushed out of the business",
  },
  {
    name: "The Tourist",
    year: 2010,
    runtime: 103,
    categories: [
      "action",
      "adventure",
      "crime",
      "mystery",
      "romance",
      "thriller",
    ],
    "release-date": "2010-12-10",
    director: "Florian Henckel von Donnersmarck",
    writer: [
      "Florian Henckel von Donnersmarck",
      "Christopher McQuarrie",
      "Julian Fellowes",
      "Jérôme Salle",
    ],
    actors: [
      "Johnny Depp",
      "Angelina Jolie",
      "Paul Bettany",
      "Timothy Dalton",
      "Steven Berkoff",
    ],
    storyline:
      "Elise (Jolie) sits next to an American tourist, Frank (Depp), on a train going to Venice. She has chosen him as a decoy, making believe that he is her lover who is wanted by police. Not only will they need to evade the police, but also the mobster whose money her lover stole.",
  },
];
